baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[markup.goldmark.parser.attribute]
block = true

[params]
description = "The personal blog of David Flood, II"

[taxonomies]
category = "categories"
tag = "tags"
